project_id = "xanbbjxvxktiupefvkha"

[functions.get-pdfs-without-thumbnails]
verify_jwt = true

[functions.summarize-pdf]
verify_jwt = true

[functions.generate-study-guide]
verify_jwt = true

[functions.pdf-to-speech]
verify_jwt = true

[functions.translate-pdf]
verify_jwt = true

[functions.translate-pdf-structured]
verify_jwt = true

[functions.chat-with-pdf]
verify_jwt = true

[functions.convert-to-pdf]
verify_jwt = true

[functions.create-rep-account]
verify_jwt = true

[functions.update-rep-account]
verify_jwt = true

[functions.notify-department-users]
verify_jwt = true

[functions.notify-timetable-change]
verify_jwt = true
